YJ2:
  ext: 2
  pnts_path: config/points20240527_143953.txt
  box_size: 30
  box1D_size: 10
  pixel_size: 0.015
  DAM_step_size: 0.01
  xpix: 4096
  ypix: 4096

HH1:  
  ext: 1
  pnts_path: config/points20240522_145947_H1.txt
  box_size: 30
  box1D_size: 10
  pixel_size: 0.015
  DAM_step_size: 0.01
  xpix: 4096
  ypix: 4096

HH2:
  ext: 2
  pnts_path: config/points20240718_105845.txt
  box_size: 30
  box1D_size: 10
  pixel_size: 0.015
  DAM_step_size: 0.01
  xpix: 4096
  ypix: 4096

RI2:
  ext: 2
  pnts_path: config/points20240508_160118.txt
  box_size: 30
  box1D_size: 10
  pixel_size: 0.015
  DAM_step_size: 0.01
  xpix: 4256
  ypix: 4256


